name: Manually Deploy to Okteto

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          usedocker: true
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
